/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InternshipRouteImport } from './routes/internship'
import { Route as CourseworkRouteImport } from './routes/coursework'
import { Route as CapstoneProposalRouteImport } from './routes/capstone-proposal'
import { Route as CapstoneProjectRouteImport } from './routes/capstone-project'
import { Route as IndexRouteImport } from './routes/index'

const InternshipRoute = InternshipRouteImport.update({
  id: '/internship',
  path: '/internship',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseworkRoute = CourseworkRouteImport.update({
  id: '/coursework',
  path: '/coursework',
  getParentRoute: () => rootRouteImport,
} as any)
const CapstoneProposalRoute = CapstoneProposalRouteImport.update({
  id: '/capstone-proposal',
  path: '/capstone-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const CapstoneProjectRoute = CapstoneProjectRouteImport.update({
  id: '/capstone-project',
  path: '/capstone-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capstone-project': typeof CapstoneProjectRoute
  '/capstone-proposal': typeof CapstoneProposalRoute
  '/coursework': typeof CourseworkRoute
  '/internship': typeof InternshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capstone-project': typeof CapstoneProjectRoute
  '/capstone-proposal': typeof CapstoneProposalRoute
  '/coursework': typeof CourseworkRoute
  '/internship': typeof InternshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capstone-project': typeof CapstoneProjectRoute
  '/capstone-proposal': typeof CapstoneProposalRoute
  '/coursework': typeof CourseworkRoute
  '/internship': typeof InternshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capstone-project'
    | '/capstone-proposal'
    | '/coursework'
    | '/internship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capstone-project'
    | '/capstone-proposal'
    | '/coursework'
    | '/internship'
  id:
    | '__root__'
    | '/'
    | '/capstone-project'
    | '/capstone-proposal'
    | '/coursework'
    | '/internship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapstoneProjectRoute: typeof CapstoneProjectRoute
  CapstoneProposalRoute: typeof CapstoneProposalRoute
  CourseworkRoute: typeof CourseworkRoute
  InternshipRoute: typeof InternshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/internship': {
      id: '/internship'
      path: '/internship'
      fullPath: '/internship'
      preLoaderRoute: typeof InternshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coursework': {
      id: '/coursework'
      path: '/coursework'
      fullPath: '/coursework'
      preLoaderRoute: typeof CourseworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capstone-proposal': {
      id: '/capstone-proposal'
      path: '/capstone-proposal'
      fullPath: '/capstone-proposal'
      preLoaderRoute: typeof CapstoneProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capstone-project': {
      id: '/capstone-project'
      path: '/capstone-project'
      fullPath: '/capstone-project'
      preLoaderRoute: typeof CapstoneProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapstoneProjectRoute: CapstoneProjectRoute,
  CapstoneProposalRoute: CapstoneProposalRoute,
  CourseworkRoute: CourseworkRoute,
  InternshipRoute: InternshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
